config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasklists do
    resources :tasks
  end

  resources :tasks do
    member do
      patch "sort"
    end
  end

  resources :task_users, only: [:update]

  resources :rooms do
    patch "join", on: :member
    resources :messages
  end

  root "homes#index"
end

app/models/tasklist.rb
# == Schema Information
#
# Table name: tasklists
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tasklist < ApplicationRecord
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy, inverse_of: :tasklist

  validates :title, presence: true
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :set_tasklist, only: %i[edit update destroy]

  def index
    @tasklists = Tasklist.all
  end

  def new
    @tasklist = Tasklist.new
  end

  def edit
  end

  def create
    @tasklist = Tasklist.new(tasklist_params)

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to tasklists_path }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tasklist.update(tasklist_params)
        format.html { redirect_to tasklists_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tasklist.destroy
    respond_to do |format|
      format.html { redirect_to tasklists_path, status: :see_other }
      format.turbo_stream
    end
  end

  private

  def set_tasklist
    @tasklist = Tasklist.find(params[:id])
  end

  def tasklist_params
    params.require(:tasklist).permit(:title)
  end
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/tasklists/_form.html.erb
<%= form_with model: @tasklist, class: "w-full", data: { controller: "form" } do |f| %>
  <% if tasklist.errors.any? %>
    <h2><%= pluralize(tasklist.errors.count, "errors") %> prohibited this tasklist to being saved.</h2>
    <% tasklist.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :title, hidden: true %>
  <%= f.text_field :title, 
    placeholder: "My tasklist", 
    class: "border border-neutral p-1 w-full" ,
    data: { "form-target": "input", action: @tasklist.persisted? ? "blur->form#submit" : "blur->form#cancel" }
  %>
  <%= f.submit nil, hidden: true, class: "border border-black cursor-pointer" %>
<% end %>

app/views/tasklists/_header.html.erb
<%= turbo_frame_tag dom_id(tasklist, :header), class: "w-[300px] flex justify-between items-center px-4 py-2 bg-primary h-12 box-border grow-0 shrink-0 rounded-t-lg" do %>
  <div class="text-primary-content">
    <%= tasklist.title %>
  </div>
  <div class="flex gap-1 text-primary-content">
    <%= render "menu", tasklist: tasklist %>
    <%= link_to new_tasklist_task_path(tasklist.id), data: { turbo_frame: dom_id(tasklist, :new_task) }, class: "p1 h-8 w-8 box-border grid place-content-center hover:bg-primary-focus rounded-full" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
    <% end %>
  </div>
<% end %>

app/views/tasklists/_menu.html.erb
<div class="relative inline-block text-left" data-controller="menu" data-action="open-menu@window->menu#closeOtherMenu">
  <div class="box-border h-8 w-8">
    <button 
      type="button" 
      data-action="click->menu#toggle"
      data-menu-target="menuButton"
      class="group inline-flex justify-center text-sm font-medium text-primary-content hover:bg-primary-focus rounded-full p-1" 
      aria-expanded="false" 
      aria-haspopup="true"
      id="<%= dom_id(tasklist, :menu) %>" 
      >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
      </svg>
    </button>
  </div>
  <div
    data-menu-target="items" 
    class="absolute right-0 z-10 mt-2 w-40 origin-top-right rounded-md bg-white shadow-2xl ring-1 ring-black ring-opacity-5 focus:outline-none" 
    role="menu" aria-orientation="vertical" 
    tabindex="-1"
    style="display:none;"
  >
    <div class="py-1" role="none">
      <%= link_to "Edit", edit_tasklist_path(tasklist.id), 
        class: "font-medium text-neutral block px-4 py-2 text-sm", 
        role: "menuitem", 
        tabindex: -1, 
        id: "edit-menu", 
        data: { action: "click->menu#toggle" } 
      %>
      <%= button_to "Delete", tasklist, 
        method: :delete, 
        class: "font-medium text-red-400 block px-4 py-2 text-sm", 
        role: "menuitem", 
        tabindex: -1, 
        id: "delete-menu", 
        data: { action: "click->menu#toggle" } 
      %>
    </div>
  </div>
</div>

app/views/tasklists/_tasklist.html.erb
<%= turbo_frame_tag dom_id(tasklist) do %>
  <div class="flex flex-col h-full gap-1">
    <%= render "tasklists/header", { tasklist: tasklist } %>
    <%= turbo_frame_tag dom_id(tasklist, :new_task) %>
    <%= turbo_frame_tag dom_id(tasklist, :tasks), data: { controller: "dnd", "tasklist-id": tasklist.id }, class: "h-full flex flex-col gap-1" do %>
      <% tasklist.tasks.each do |task| %>
        <%= render "tasks/task", { tasklist: tasklist, task: task } %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/tasklists/create.turbo_stream.erb
<%= turbo_stream.append :tasklists, partial: "tasklists/tasklist", locals: { tasklist: @tasklist } %>
<%= turbo_stream.update Tasklist.new, "" %>

app/views/tasklists/destroy.turbo_stream.erb
<%= turbo_stream.remove @tasklist %>

app/views/tasklists/edit.html.erb
<h1 class="text-xl">Edit Tasklist Page</h1>
<%= turbo_frame_tag dom_id(@tasklist, :header) do %>
  <%= render "form", tasklist: @tasklist %>
<% end %>

app/views/tasklists/index.html.erb
<div class="flex gap-3">
  <div id="tasklists" class="flex gap-3">
    <%= render @tasklists %>
  </div>
  <%= turbo_frame_tag dom_id(Tasklist.new) %>
  <%= link_to "Create List", new_tasklist_path, data: { turbo_frame: dom_id(Tasklist.new) }, class: "text-accent btn btn-link"  %>
</div>

app/views/tasklists/new.html.erb
<h1 class="text-2xl">Create tasklist</h1>
<%= turbo_frame_tag @tasklist do %>
  <div class="w-[300px] flex justify-between items-center px-4 py-2 bg-primary h-12 box-border grow-0 shrink-0 rounded-t-lg">
    <%= render "form", tasklist: @tasklist %>
  </div>
<% end %>