config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasklists do
    resources :tasks
  end

  resources :tasks do
    member do
      patch "sort"
    end
  end

  resources :task_users, only: [:update]

  resources :rooms do
    patch "join", on: :member
    resources :messages
  end

  root "homes#index"
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :string
#  completed   :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tasklist_id :integer          not null
#  position    :integer
#
class Task < ApplicationRecord
  belongs_to :tasklist
  has_many :task_users, dependent: :destroy
  has_many :users, through: :task_users

  delegate :assignees, to: :task_users
  delegate :followers, to: :task_users

  acts_as_list scope: :tasklist
  validates :title, presence: true

  scope :ordered, -> { order(created_at: :desc) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasklist, only: [:show, :new, :create, :edit, :update]
  before_action :set_task, only: [:edit, :update, :destroy, :sort]

  def show
    @users = User.all
    @task = Task.includes(:task_users).find(params[:id])
  end

  def new
    @task = @tasklist.tasks.build
  end

  def edit
  end

  def create
    @task = @tasklist.tasks.build(task_params)
    @task.insert_at(1)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasklists_path }
        format.turbo_stream { flash.now[:notice] = "Task was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @users = User.all
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasklists_path }
        format.turbo_stream { flash.now[:notice] = "Task was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other }
      format.turbo_stream { flash.now[:notice] = "Task was successfully removed." }
    end
  end

  def sort
    @task.insert_at(sort_params[:position])

    if @task.update(sort_params)
      head :ok
    else
      redirect_to tasklists_path, status: :internal_server_error
    end
  end

  private

  def set_tasklist
    @tasklist = Tasklist.find(params[:tasklist_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def sort_params
    params.require(:task).permit(:position, :tasklist_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: [tasklist, task], class: "flex flex-col" do |f| %>
  <% if task.errors.any? %>
    <h2>
      <%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:
    </h2>
    <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title, "Task title", hidden: true %>
  <%= f.text_field :title, 
    placeholder: "My task", 
    autofocus: true, 
    class: "bg-base-100 border border-neutral text-neutral text-sm focus:ring-primary block p-3 h-10 box-border"  
  %>
  <div class="flex gap-4 py-2 flex-row-reverse">
    <%= f.submit nil, class: "btn btn-sm" %>
    <% if @task.persisted? %>
      <%= link_to "Cancel", tasklist_task_path(tasklist, task), class: "btn btn-ghost btn-sm" %>
    <% else %>
      <%= link_to "Cancel", tasklists_path, class: "btn btn-ghost btn-sm" %>
    <% end %>
  </div>
<% end %>

app/views/tasks/_show_task.html.erb
<%= turbo_frame_tag :modal_content do %>
  <%= turbo_frame_tag dom_id(task, :show) do %>
    <h1 class='text-2xl font-bold'>
      <%= task.title %>
    </h1>
  <% end %>
  <div class="flex mt-5 items-center">
    <%= render "task_users/task_users", { task: task, users: users } %>
  </div>
  <div class="flex gap-2 mt-5">
    <%= link_to "Edit task", edit_tasklist_task_path(tasklist, task), data: { turbo_frame: dom_id(task, :show) }, class: "text-primary" %>
    <%= button_to "Delete task", [tasklist, task], method: :delete, data: { action: "click->modal#close" }, class: "text-error"  %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task), data: { "task-id": task.id }, target: :modal_content do %>
  <%= link_to tasklist_task_path(tasklist, task), class: "flex flex-col gap-2 bg-base-100 shadow-md px-4 py-3 max-w-md text-neutral cursor-grab" do %>
    <%= task.title %>
    <% unless task.assignees.empty? %>
      <div class="avatar-group -space-x-3">
        <% task.assignees.each do |assignee| %>
          <div class="avatar">
            <div class="w-6 rounded-full">
              <%= image_tag avatar_img_for(assignee.user, :avatar_sm) %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end%>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@tasklist, :tasks), partial: "tasks/task", locals: { tasklist: @tasklist, task: @task } %>
<%= turbo_stream.update dom_id(@tasklist, :new_task), "" %>
<%= render_turbo_stream_flash_messages %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove @task %>
<%= turbo_stream.update :modal_content, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/tasks/edit.html.erb
<div class="text-2xl font-bold">Edit task</div>
<%= turbo_frame_tag dom_id(@task, :show) do %>
  <div class="max-w-md">
    <%= render "form", task: @task, tasklist: @tasklist %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<div class='max-w-md'>
  <%= turbo_frame_tag dom_id(@tasklist, :new_task) do %>
    <%= render "form", task: @task, tasklist: @tasklist %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<%= render "show_task", { task: @task, tasklist: @tasklist, users: @users } %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace @task, partial: "tasks/task", locals: { tasklist: @tasklist, task: @task } %>
<%= turbo_stream.replace :modal_content, partial: "tasks/show_task", locals: { tasklist: @tasklist, task: @task, users: @users } %>
<%= render_turbo_stream_flash_messages %>