config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasklists do
    resources :tasks
  end

  resources :tasks do
    member do
      patch "sort"
    end
  end

  resources :task_users, only: [:update]

  resources :rooms do
    patch "join", on: :member
    resources :messages
  end

  root "homes#index"
end

app/models/task_user.rb
# == Schema Information
#
# Table name: task_users
#
#  id         :integer          not null, primary key
#  task_id    :integer          not null
#  user_id    :integer          not null
#  role       :integer          default("followers")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TaskUser < ApplicationRecord
  enum :role, [:followers, :assignees]

  belongs_to :task
  belongs_to :user
end

app/controllers/task_users_controller.rb
class TaskUsersController < ApplicationController
  def update
    @task_user = TaskUser.find_or_initialize_by(task_id: params[:task_id], user_id: params[:user_id])
    @task_user.role = params[:role]

    @task = Task.includes(:task_users).find(params[:task_id])
    @task_users = @task.task_users
    @users = User.all

    respond_to do |format|
      if @task_user.save!
        format.turbo_stream {}
        format.html { redirect_to tasklists_path }
      else
        format.html { render :root, status: :unprocessable_entity }
        format.turbo_stream { flash.now[:alert] = "Fail to update task user." }
      end
    end
  end

  private

  def task_users_params
    params.require(:task_users).permit(:task_id, :user_id, :role)
  end
end

app/helpers/task_users_helper.rb
module TaskUsersHelper
  def assignable_users(users, task, role)
    if task.users.empty?
      users
    else
      excluded_user_ids = task.task_users.where(role: role.to_sym).pluck(:user_id)

      users.reject { |user| excluded_user_ids.include? user.id }
    end
  end
end

app/views/task_users/_task_users.html.erb
<%= turbo_frame_tag dom_id(task, :users) do %>
  <div class="flex flex-col gap-4">
    <div class="flex gap-1 items-center">
      <p>Assign to</p>
      <div class="avatar-group -space-x-3">
        <% task.assignees.each do |assignee| %>
          <div class="avatar">
            <div class="w-6 rounded-full">
              <%= image_tag avatar_img_for(assignee.user, :avatar_sm) %>
            </div>
          </div>
        <% end %>
      </div>
      <%= render "task_users/users_select", { users: assignable_users(users, task, :assignees), task: task, role: :assignees } %>
    </div>
    <div class="flex gap-1 items-center">
      <p>Follow by</p>
      <div class="avatar-group -space-x-3">
        <% task.followers.each do |follower| %>
          <div class="avatar">
            <div class="w-6 rounded-full">
              <%= image_tag avatar_img_for(follower.user, :avatar_sm) %>
            </div>
          </div>
        <% end %>
      </div>
      <%= render "task_users/users_select", { users: assignable_users(users, task, :followers), task: task, role: :followers } %>
    </div>
  </div>
<% end %>

app/views/task_users/_users_select.html.erb
<%= turbo_frame_tag dom_id(@task, "#{role}_select") do %>
  <div class="dropdown dropdown-bottom">
    <label tabindex="0" class="btn btn-sm btn-circle btn-ghost p-2 grid place-content-center box-border">
      <span role="img">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
        </svg>
      </span>
    </label>
    <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
      <% users.each do |user| %>
        <li>
          <%= button_to user.email, task_user_path(task_id: task.id, user_id: user.id, role: role), method: :put  %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/task_users/index.hml.erb
<h1 class="font-bold text-2xl">Task Users</h1>
<%= render "task_users", { users: @users, task_id: @task.id, task_users: @task_users } %>

app/views/task_users/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@task, :users), partial: "task_users/task_users", locals: { task: @task, users: @users } %>
<%= turbo_stream.replace dom_id(@task), partial: "tasks/task", locals: { task: @task, tasklist: @task.tasklist } %>