config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasklists do
    resources :tasks
  end

  resources :tasks do
    member do
      patch "sort"
    end
  end

  resources :task_users, only: [:update]

  resources :rooms do
    patch "join", on: :member
    resources :messages
  end

  root "homes#index"
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  accepts_nested_attributes_for :users

  validates :title, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[edit update destroy]

  def index
    @rooms = Room.all
  end

  def show
    @message = Message.new
    @room = Room.includes(:messages).find(params[:id])
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)
    @room.users << current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_path }
    end
  end

  def join
    @room = Room.find(params[:room_id])
    respond_to do |format|
      if @room.update(users: @room.users.push(current_user))
        format.html { redirect_to @room }
      else
        format.html { render @room, status: :unprocessable_entity }
      end
    end
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def is_room_user(room, user)
    room.users.any? { |room_user| room_user.id === user.id }
  end
end

app/views/rooms/_form.html.erb
<%= form_with model: @room, class: "w-96 mx-auto shadow rounded p-8 form-control border-t-4 border-primary bg-base-100" do |f| %>
  <% if room.errors.any? %>
    <h2><%= pluralize(room.errors.count, "errors") %> prohibited this room from being saved.</h2>
    <% room.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label :title, class: "label" %>
  <%= f.text_field :title, 
    placeholder: "Room name", 
    class: "input input-bordered w-full" 
  %>
  <%= f.submit nil, class: "btn btn-primary w-full mt-8" %>
  <%= link_to "cancel", @room, class: "capitalize mt-4 link text-center text-sm" %>
<% end %>

app/views/rooms/_menu.html.erb
<div class="relative inline-block text-left" data-controller="menu">
  <div class="box-border h-8 w-8">
    <button 
      type="button" 
      data-action="click->menu#toggle"
      data-menu-target="menuButton"
      class="group inline-flex justify-center text-sm font-medium text-neutral hover:bg-base-300 rounded-full p-1" 
      id="menu-button" 
      aria-expanded="false" 
      aria-haspopup="true"
      >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
      </svg>
    </button>
  </div>
  <div
    data-menu-target="items" 
    class="absolute right-0 z-10 mt-2 w-40 origin-top-right rounded-md bg-white shadow-2xl ring-1 ring-black ring-opacity-5 focus:outline-none" 
    role="menu" aria-orientation="vertical" 
    aria-labelledby="menu-button" 
    tabindex="-1"
    style="display:none;"
  >
    <div class="py-1" role="none">
      <%= link_to "Edit", edit_room_path(room.id), 
        class: "font-medium text-neutral block px-4 py-2 text-sm", 
        role: "menuitem", 
        tabindex: -1, 
        id: "edit-menu", 
        data: { action: "click->menu#toggle" } 
      %>
      <%= button_to "Delete", room, 
        method: :delete, 
        class: "font-medium text-red-400 block px-4 py-2 text-sm", 
        role: "menuitem", 
        tabindex: -1, 
        id: "delete-menu", 
        data: { action: "click->menu#toggle" } 
      %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render "form", room: @room %>

app/views/rooms/index.html.erb
<div class="text-lg">Chat Rooms</div>
<ul class="mb-8">
  <% @rooms&.each do |room| %>
    <li>
      <%= link_to room.title, room, class: "text-primary hover:underline"%>
    </li>
  <% end %>
</ul>
<%= link_to "Create Room", new_room_path, class: "text-primary hover:underline" %>

app/views/rooms/new.html.erb
<%= render "form", room: @room %>

app/views/rooms/show.html.erb
<div class="w-[650px] mx-auto shadow bg-base-100" data-controller="room">
  <div class="h-16 px-6 py-4 border-b-2 border-base-300 flex justify-between">
    <div class="font-semibold text-gray-700">
      <%= @room.title %>
    </div>
    <%= render "menu", room: @room %>
  </div>
  <div class="h-[400px] px-10 py-7 overflow-y-auto" data-room-target="chatPane">
    <% if is_room_user(@room, current_user) %>
      <%= turbo_frame_tag dom_id(@room, :messages) do %>
        <% @room.messages.each do |message| %>
          <%= render "messages/message", { message: message, user_id: current_user.id } %>
        <% end %>
      <% end %>
      <%= turbo_stream_from dom_id(@room, :messages) %>
    <% else %>
      <%= button_to "Join", join_room_path(room_id: @room.id), method: :patch, class: "btn btn-outline" %>
    <% end %>
  </div>
  <%= form_with model: [@room, @message], data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>
    <%= content_tag :fieldset, class: "flex h-12", disabled: !is_room_user(@room, current_user) do %>
      <%= f.text_field :body, data: { "form-target": "input" }, placeholder: "Enter Message", class: "w-full border bg-base-200 px-4 py-2 focus:ring-2 focus:ring-primary focus-visible:outline-none" %>
      <%= f.submit "Send", class: "btn rounded-none disabled:btn-disabled" %>
    <% end %>
  <% end %>
</div>